apiVersion: container.cnrm.cloud.google.com/v1beta1
kind: ContainerCluster
metadata: # kpt-merge: config-control/example-us-east4
  name: mxclusternew # kpt-set: ${cluster-name}
  namespace: config-control # kpt-set: ${platform-namespace}
  annotations:
    cnrm.cloud.google.com/blueprint: cnrm/gke:gke-cluster/v0.4.0,kpt-pkg-fn-live
    cnrm.cloud.google.com/project-id: searce-sandbox-355505 # kpt-set: ${project-id}
    cnrm.cloud.google.com/remove-default-node-pool: "true"
spec:
  addonsConfig:
    dnsCacheConfig:
      enabled: true
    gcePersistentDiskCsiDriverConfig:
      enabled: true
  enableBinaryAuthorization: true
  enableShieldedNodes: true
  initialNodeCount: 1
  ipAllocationPolicy:
    clusterSecondaryRangeName: pods # kpt-set: ${pods-range-name}
    servicesSecondaryRangeName: services # kpt-set: ${services-range-name}
  location: australia-southeast1 # kpt-set: ${location}
  masterAuthorizedNetworksConfig:
    cidrBlocks:
      - cidrBlock: 0.0.0.0/0
        displayName: Whole Internet
  networkRef:
    external: projects/searce-sandbox-355505/global/networks/mxvpcnew # kpt-set: ${network-ref}
  privateClusterConfig:
    enablePrivateEndpoint: false
    enablePrivateNodes: true
    masterGlobalAccessConfig:
      enabled: true
    masterIpv4CidrBlock: 10.254.0.0/28 # kpt-set: ${master-ip-range}
  datapathProvider: ADVANCED_DATAPATH
  loggingConfig:
    enableComponents:
      - SYSTEM_COMPONENTS
      - WORKLOADS
  monitoringConfig:
    enableComponents:
      - SYSTEM_COMPONENTS
  releaseChannel:
    channel: REGULAR
  subnetworkRef:
    external: projects/searce-sandbox-355505/regions/australia-southeast1/subnetworks/mxsubnet # kpt-set: ${subnet-ref}
  verticalPodAutoscaling:
    enabled: true
  workloadIdentityConfig:
    identityNamespace: searce-sandbox-355505.svc.id.goog # kpt-set: ${project-id}.svc.id.goog
