apiVersion: serviceusage.cnrm.cloud.google.com/v1beta1
kind: Service
metadata: # kpt-merge: projects/project-id-cluster-name-container
  name: searce-sandbox-355505-mxclusternew-container # kpt-set: ${project-id}-${cluster-name}-container
  namespace: config-control # kpt-set: ${projects-namespace}
  annotations:
    cnrm.cloud.google.com/blueprint: cnrm/gke:gke-cluster/v0.4.0,kpt-pkg-fn-live
    cnrm.cloud.google.com/deletion-policy: abandon
    cnrm.cloud.google.com/project-id: searce-sandbox-355505 # kpt-set: ${project-id}
spec:
  resourceID: container.googleapis.com
