apiVersion: v1
kind: ConfigMap
metadata:
  name: setters
  namespace: config-control
data:
  network-name: xyzw
  project-id: searce-sandbox-355505
  region: australia-southeast1
  prefix: nat
  cluster-name: mxclusternew
  # The compute location (region for a regional cluster or zone for a zonal cluster)
  location: australia-southeast1
  # The private IP range for masters to use when peering to the VPC
  master-ip-range: 10.254.0.0/28
  # The reference to the network
  network-ref: projects/searce-sandbox-355505/global/networks/mxvpcnew
  # The reference to the subnet
  subnet-ref: projects/searce-sandbox-355505/regions/australia-southeast1/subnetworks/mxsubnet
  # The namespace in which to manage cluster resources
  platform-namespace: config-control
  # The project in which to manage cluster resources
  # The namespace in which g
  projects-namespace: config-control
  # The private IP range name for pods to use, this range must already exist
  pods-range-name: pods
  # The private IP range name for services to use, this range must already exist
  services-range-name: services
  # The group in which to manage the list of groups that can be used for RBAC.
  # Must be named exactly 'gke-security-groups'.
  security-group: gke-security-groups@example.com
